language: node_js
node_js:
- '0.10'
sudo: false
env:
  global:
  - SAUCE_USERNAME=htmlbars-ci
  - SAUCE_ACCESS_KEY=71947947-f373-4e9c-9166-23038df7ddf2
  matrix:
  - TEST_NODE=1 TEST_BROWSERS=1
matrix:
  fast_finish: true
before_script:
  - curl -L https://gist.githubusercontent.com/johanneswuerbach/ce15304c6d33538ecc6e/raw/sauce-connect.sh | bash
after_script:
  - sleep 10
  - killall sc
