---
rvm:
- 2.1.0
node_js:
- "0.10"
install:
- "npm install"
- "bin/cached-bundle install --deployment --retry 3 --jobs 4"
after_success: bundle exec rake publish_build
script: rake test\[$TEST_SUITE]
notifications:
  campfire:
    rooms:
    - secure: ! 'ia5CUz3FeqK+s238B9ApRz1vt/qpM/WtI5HlYS7GH5WPBbC5vsSUIwV9IqM8

        HKvTwLQKHUP5e+6I7E40/ofbQycsNSeglJ0mRRzdLe2SeN68uPsjuy5AKnpn

        KpIzGa9OC5tZfN/RqJskLuP8QRvqNCLPyesY1E5GM7lTKYa92PM='
    on_success: change
    on_failure: always
env:
  global:
  - S3_BUILD_CACHE_BUCKET=emberjs-build-cache
  - S3_BUCKET_NAME=builds.emberjs.com
  - secure: ! 'KXJmcGLpnxnPmmei/qPNVcdQxLX1xyYIaVocinQ0YAjtBvCtAwg63EWMFnGp

      VIzUNikE+Cej3g+nwEdDJiL1c9NFPL+zCnriR2iMVjPak+IQaG3YcMm0T+hY

      /WLEPAquZBKw1gU6lBEUuDumTlkXQQdHz3cJYoidAXz3uV1EXIU='
  - secure: ! 'qCW0BVNFuQjAI53pvvE6oeGxtEdZ+RlvcCpYjU4vxEjedidEEcHKtIVh7d7J

      PZ8DNTxX0zsp2jjY8NwTR5MC8NBH+J5VjuTSGv82t5sm0i0jzaBmOOSLbKqH

      I/BFT0MbnR6JVCZiPV7TCWPgY1gvgZ6TEEIKGqauDMUBdL8ZK6I='
  matrix:
    - MULTI_BRANCH_TESTS=false TEST_SUITE=packages
    - MULTI_BRANCH_TESTS=false TEST_SUITE=old_jquery
    - MULTI_BRANCH_TESTS=false TEST_SUITE=extend_prototypes
    - MULTI_BRANCH_TESTS=false TEST_SUITE=built
    - MULTI_BRANCH_TESTS=false TEST_SUITE=standard FORCE_BRANCH=beta
    - MULTI_BRANCH_TESTS=false TEST_SUITE=standard FORCE_BRANCH=stable
