language: node_js
node_js:
  - 6
sudo: false
cache: yarn
before_install:
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH
env:
  global:
    - SAUCE_USERNAME=htmlbars-ci
    - SAUCE_ACCESS_KEY=71947947-f373-4e9c-9166-23038df7ddf2
  matrix:
    - TEST_NODE=1 TEST_BROWSERS=1
matrix:
  fast_finish: true
before_script:
  - yarn run sauce:connect
script:
  - yarn run problems
  - yarn run test:ci
  - yarn run build
after_script:
  - sleep 10
  - yarn run sauce:disconnect
