---
language: node_js
node_js:
  - "iojs"

sudo: false

cache:
  directories:
    - node_modules
    - bower_components
    - persistent-filter-caches

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm --version"
  - "phantomjs --version"

install:
  - "npm install"

after_success:
  - "./bin/publish_builds"

script:
  - npm test

branches:
  only:
    - master
    - beta
    - stable

env:
  global:
    - SAUCE_USERNAME=ember-ci
    - SAUCE_ACCESS_KEY=b5cff982-069f-4a0d-ac34-b77e57c2e295
    - DISABLE_SOURCE_MAPS=true
    - BROCCOLI_ENV=production
    - S3_BUILD_CACHE_BUCKET=emberjs-build-cache
    - S3_BUCKET_NAME=builds.emberjs.com
    - BROCCOLI_PERSISTENT_FILTER_CACHE_ROOT=persistent-filter-caches
    - secure: "SHnuJ4A3QbSc3LV2fYynDPbbSbhVl0ZWnCiKPuRgwnddDnoSaMQUY2RqyHdtsQGdUZCOeNaMvYUhYx6hzxBVHn0yuN3KA20aSwvYdwaMgZXfJi+lyxgsEI8iYdksWXvVbCAyKM8zjTWXUtNcMBGtsGYOfdD41wfZgI8GsI0YYJc="
    - secure: ! 'KXJmcGLpnxnPmmei/qPNVcdQxLX1xyYIaVocinQ0YAjtBvCtAwg63EWMFnGp

      VIzUNikE+Cej3g+nwEdDJiL1c9NFPL+zCnriR2iMVjPak+IQaG3YcMm0T+hY

      /WLEPAquZBKw1gU6lBEUuDumTlkXQQdHz3cJYoidAXz3uV1EXIU='
    - secure: ! 'qCW0BVNFuQjAI53pvvE6oeGxtEdZ+RlvcCpYjU4vxEjedidEEcHKtIVh7d7J

      PZ8DNTxX0zsp2jjY8NwTR5MC8NBH+J5VjuTSGv82t5sm0i0jzaBmOOSLbKqH

      I/BFT0MbnR6JVCZiPV7TCWPgY1gvgZ6TEEIKGqauDMUBdL8ZK6I='
    - secure: e0yxVfwVW61d3Mi/QBOsY6Rfd1mZd3VXUd9xNRoz/fkvQJRuVwDe7oG3NOuJ4LZzvMw7BJ+zpDV9D8nKhAyPEEOgpkkMHUB7Ds83pHG4qSMzm4EAwBCadDLXCQirldz8dzN5FAqgGucXoj5fj/p2SKOkO6qWIZveGr8pdBJEG1E=
  matrix:
    - TEST_SUITE=each-package-tests
    - TEST_SUITE=built-tests EMBER_ENV=production DISABLE_JSCS=true DISABLE_JSHINT=true
    - TEST_SUITE=old-jquery-and-extend-prototypes
    - TEST_SUITE=node DISABLE_JSCS=true DISABLE_JSHINT=true
    - TEST_SUITE=sauce
