---
rvm:
- 1.9.3
node_js:
- "0.10"
install:
- "npm install -g defeatureify"
- "npm install -g yuidocjs"
- "bundle install --deployment"
after_success: bundle exec rake publish_build
script: rake test\[$TEST_SUITE]
notifications:
  campfire:
    rooms:
    - secure: ! 'ia5CUz3FeqK+s238B9ApRz1vt/qpM/WtI5HlYS7GH5WPBbC5vsSUIwV9IqM8

        HKvTwLQKHUP5e+6I7E40/ofbQycsNSeglJ0mRRzdLe2SeN68uPsjuy5AKnpn

        KpIzGa9OC5tZfN/RqJskLuP8QRvqNCLPyesY1E5GM7lTKYa92PM='
    on_success: change
    on_failure: always
env:
  global:
  - S3_BUCKET_NAME=builds.emberjs.com
  - secure: ! 'KXJmcGLpnxnPmmei/qPNVcdQxLX1xyYIaVocinQ0YAjtBvCtAwg63EWMFnGp

      VIzUNikE+Cej3g+nwEdDJiL1c9NFPL+zCnriR2iMVjPak+IQaG3YcMm0T+hY

      /WLEPAquZBKw1gU6lBEUuDumTlkXQQdHz3cJYoidAXz3uV1EXIU='
  - secure: ! 'qCW0BVNFuQjAI53pvvE6oeGxtEdZ+RlvcCpYjU4vxEjedidEEcHKtIVh7d7J

      PZ8DNTxX0zsp2jjY8NwTR5MC8NBH+J5VjuTSGv82t5sm0i0jzaBmOOSLbKqH

      I/BFT0MbnR6JVCZiPV7TCWPgY1gvgZ6TEEIKGqauDMUBdL8ZK6I='
  matrix:
    - TEST_SUITE=packages
    - TEST_SUITE=old_jquery
    - TEST_SUITE=extend_prototypes
    - TEST_SUITE=built
