language: node_js
sudo: required
dist: trusty

node_js:
  - "6"

addons:
  firefox: "latest"

cache:
  directories:
  - $HOME/.yarn-cache

before_install:
- |
    phantomjs --version
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start

    sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt-get update -qq
    sudo apt-get install -y -qq yarn
    yarn --version

install:
- |
    yarn install

after_success:
  - "./bin/publish_builds"

branches:
  only:
    - master
    - beta
    - stable
    # npm version tags
    - /^v\d+\.\d+\.\d+/

env:
  global:
    - SAUCE_USERNAME=ember-ci
    - SAUCE_ACCESS_KEY=b5cff982-069f-4a0d-ac34-b77e57c2e295
    - DISABLE_SOURCE_MAPS=true
    - BROCCOLI_ENV=production
    - S3_BUCKET_NAME=builds.emberjs.com
    - secure: "SHnuJ4A3QbSc3LV2fYynDPbbSbhVl0ZWnCiKPuRgwnddDnoSaMQUY2RqyHdtsQGdUZCOeNaMvYUhYx6hzxBVHn0yuN3KA20aSwvYdwaMgZXfJi+lyxgsEI8iYdksWXvVbCAyKM8zjTWXUtNcMBGtsGYOfdD41wfZgI8GsI0YYJc="
    - secure: ! 'KXJmcGLpnxnPmmei/qPNVcdQxLX1xyYIaVocinQ0YAjtBvCtAwg63EWMFnGp

      VIzUNikE+Cej3g+nwEdDJiL1c9NFPL+zCnriR2iMVjPak+IQaG3YcMm0T+hY

      /WLEPAquZBKw1gU6lBEUuDumTlkXQQdHz3cJYoidAXz3uV1EXIU='
    - secure: ! 'qCW0BVNFuQjAI53pvvE6oeGxtEdZ+RlvcCpYjU4vxEjedidEEcHKtIVh7d7J

      PZ8DNTxX0zsp2jjY8NwTR5MC8NBH+J5VjuTSGv82t5sm0i0jzaBmOOSLbKqH

      I/BFT0MbnR6JVCZiPV7TCWPgY1gvgZ6TEEIKGqauDMUBdL8ZK6I='
    - secure: e0yxVfwVW61d3Mi/QBOsY6Rfd1mZd3VXUd9xNRoz/fkvQJRuVwDe7oG3NOuJ4LZzvMw7BJ+zpDV9D8nKhAyPEEOgpkkMHUB7Ds83pHG4qSMzm4EAwBCadDLXCQirldz8dzN5FAqgGucXoj5fj/p2SKOkO6qWIZveGr8pdBJEG1E=
  matrix:
    - TEST_SUITE=each-package-tests PUBLISH=true
    - TEST_SUITE=built-tests EMBER_ENV=production DISABLE_JSCS=true DISABLE_JSHINT=true
    - TEST_SUITE=old-jquery-and-extend-prototypes DISABLE_JSCS=true DISABLE_JSHINT=true
    - TEST_SUITE=node DISABLE_JSCS=true DISABLE_JSHINT=true
    - TEST_SUITE=blueprints
    - TEST_SUITE=travis-browsers DISABLE_JSCS=true DISABLE_JSHINT=true
    - TEST_SUITE=sauce
    - TEST_SUITE=allow-backtracking-rerender ALLOW_BACKTRACKING=true
    - TEST_SUITE=each-package-tests BUILD_TYPE=alpha PUBLISH=true
